### ISSUE TITLE
Add option to use staging URL/credentials

### ISSUE THREAD

**Issue by HugoDF** [solidgoldpig/mondo-bank#26]
Mondo have made a staging platform available, currently the easiest ways to use this as opposed to the live API is to:
1. modify the file in NPM modules
2. add a rewrite script to npm post-install hook

Have I missed something? What would be the best way to implement this option?

**Comment by solidgoldpig** [comment]
Hi Hugo

There's a setHost method now which allows you to override the prodiction value

(I'm currently totally rewriting everything, so that's the best for now ;)

**Comment by solidgoldpig** [comment]
Done in v0.1.11
